### ISSUE TITLE
Слайдер с продукцией

### ISSUE THREAD

**Issue by igosheva** [Harzu/LoftSchoolproject-2#10]
slider-box__item - это только один элемент слайдера, а таких слайдов у тебя будет много) так что сделай обертку для этого элемента с тегом ul, а этот элемент у тебя будет li.

**Comment by igosheva** [comment]
tooltip__content - этот элемент должен появляться при ховере на tooltip__but, так что его нужно положить внутри tooltip__but и реализовать его показ.

**Comment by igosheva** [comment]
tooltip__content - у этого элемента по макету еще есть border-radius и шрифт внутри не такой жирный.

**Comment by igosheva** [comment]
tooltip - у этого элемента есть border-radius: .3125rem; и цвет более яркий.

**Comment by igosheva** [comment]
slider-order__but - кнопке нужно добавить стили для hover

**Comment by Harzu** [comment]
Зделанно
