### ISSUE TITLE
Секция с командой

### ISSUE THREAD

**Issue by igosheva** [Harzu/LoftSchoolproject-2#11]
Контент должен быть по вертикале не по центру) http://joxi.ru/krD0EM7i0gMD6r

**Comment by igosheva** [comment]
team-block - у этого элемента нужно добавить паддинг сверху как по макету, чтобы если контент будет сверху он не прилип к верхней границе секции.

**Comment by igosheva** [comment]
team__name:before - стрелки по дефолту должны быть опущены вниз. При ховере на элемент team__item стрелка должна переворачиваться

**Comment by igosheva** [comment]
http://joxi.ru/brRpRZdtQLyXl2 -  картинки нет. Все из-за того, что указан не первый путь до нее

**Comment by igosheva** [comment]
team__info - в целом секция отстилизована не верно

**Comment by igosheva** [comment]
team__name - этот элемент по семантике должен быть ссылкой, потому что кликая по нему будет появляться контент.

**Comment by Harzu** [comment]
сделано
