### ISSUE TITLE
Секция с меню

### ISSUE THREAD

**Issue by igosheva** [Harzu/LoftSchoolproject-2#12]
menu__block - этот элемент по семантике должен быть ссылкой, потому что кликая по нему будет появляться контент.

**Comment by igosheva** [comment]
menu__content-text - стилизация не по макету

**Comment by igosheva** [comment]
http://joxi.ru/Dr8OkMoSkJkPjA - элемент вылез за пределы страницы. Разрешение 480px

**Comment by Harzu** [comment]
Сделаль
