### ISSUE TITLE
Элементы формы

### ISSUE THREAD

**Issue by igosheva** [Harzu/LoftSchoolproject-2#13]
order__input, order__camment-text - добавить паддинги справа. И для текстареа паддинг снизу, чтобы текст не прилипал к стенкам элементов

**Comment by igosheva** [comment]
Посмотри чтобы у всех элементов сначала были указаны классы, а уже потом атрибуты.

**Comment by igosheva** [comment]
http://joxi.ru/Drl9e0Eu4G4nLm - форма вылезла за пределы страницы. Разрешение 480px

**Comment by Harzu** [comment]
сделанно
