### ISSUE TITLE
Секция со слайдером

### ISSUE THREAD

**Issue by igosheva** [Harzu/LoftSchoolproject-2#15]
http://joxi.ru/RmzVwZvHWjoZQm - сделай на одном уровне кнопку и текст

**Comment by igosheva** [comment]
.burgers изменить значение ширины с 100vw на 100%

**Comment by igosheva** [comment]
Если значение свойства равно 0, то единицы измерения(px, rem) можно не ставить

**Comment by igosheva** [comment]
Если есть какие-то фиксированные значения ширины - лучше уйти от этого, так как это влияет на адаптив. При 480px контент залазиет под страницу http://joxi.ru/D2PG1Y9cdJDQZm

**Comment by Harzu** [comment]
вроде как сделал и слайдер допили теперь при смене ширины он по разному не реагирует
