### ISSUE TITLE
Секция с формой

### ISSUE THREAD

**Issue by igosheva** [Harzu/LoftSchoolproject-2#17]
http://joxi.ru/l2ZE0R9f87bb4m - тут контент залазиет под страницу. это происходит потому что внутри у тебя есть фиксированные значения в rem. В адаптиве нужно избегать фиксированных значений в целом. Лучше если хочешь растянуть элемент на определенную ширину задавать max-width в rem и width в %.

**Comment by igosheva** [comment]
order__block - убрать width: 100vw; при 480px и все фиксированные значения ширины для этого блока в других медиазапросах

**Comment by Harzu** [comment]
сделал перевел все в проценты
