### ISSUE TITLE
Отступы между элементами

### ISSUE THREAD

**Issue by igosheva** [Harzu/LoftSchoolproject-2#5]
quality__item - верхние внутренние отступы можно перенести заголовку(нижний внешний отступ)

**Comment by igosheva** [comment]
quality - добавить верхний внутренний отступ, а то если сейчас уберешь justify-content: center; весь контент прилипает кверху

**Comment by igosheva** [comment]
team-list__item - элементы отталкивать от друг друга лучше за счет внешних нижних отступов

**Comment by Harzu** [comment]
Исправил

но в секции Мы лучшие да и во многих других весь контент мы отцентровываем на всех экранах если добовлять злощасные падинги то контент не будет отцентрован разве что так будет выглядеть только в том разрешении макета

**Comment by igosheva** [comment]
Ладно, оставь так если хочешь, чтобы реально по центру было)
